# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - vaatodev

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://vaatodev.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_dc5a0c41809f4d26ab5820ef88a455be }}
        password: ${{ secrets.AzureAppService_ContainerPassword_91428e975bcf4e759ad79d16fe8a7171 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: vaatodev.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_dc5a0c41809f4d26ab5820ef88a455be }}/vaatodev:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'vaatodev'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ac474d35c02e4b12bd5ad13d1537ac2f }}
        images: 'vaatodev.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_dc5a0c41809f4d26ab5820ef88a455be }}/vaatodev:${{ github.sha }}'